from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium import webdriver
driver = webdriver.Chrome(executable_path='C:/chromedriver.exe')
driver = webdriver.Chrome(executable_path='C:/chromedriver.exe')
driver.maximize_window()
driver.get("http://practice.automationtesting.in/")
shop = driver.find_element_by_id('menu-item-40')
shop.click()
driver.execute_script("window.scrollBy(0, 300);")
book_buy = driver.find_element_by_css_selector('[href="/shop/?add-to-cart=182"]')
book_buy.click()
cart = driver.find_element_by_class_name('wpmenucart-icon-shopping-cart-0')
cart.click()
proceed_btn = WebDriverWait(driver, 20).until(
EC.element_to_be_clickable((By.CSS_SELECTOR, "checkout-button")) )
proceed_btn.click()
first_name = WebDriverWait(driver, 20).until(
EC.element_to_be_clickable((By.ID, "billing_first_name")) )
first_name.send_keys("Irina")
last_name = driver.find_element_by_id('billing_last_name')
last_name.send_keys("Lobysheva")
email = driver.find_element_by_id('billing_email')
email.send_keys("sami-s-ysami@yandex.ru")
phone = driver.find_element_by_id('billing_phone')
phone.send_keys("+79252760206")
country = driver.find_element_by_class_name('select2-arrow')
country.click()
country1 = driver.find_element_by_id('s2id_autogen1_search')
country1.send_keys("Russia")
country_select = driver.find_element_by_id('select2-results-1')
country_select.click()
address = driver.find_element_by_id('billing_address_1')
address.send_keys("Lenina 1")
city = driver.find_element_by_id('billing_city')
city.send_keys("Moscow")
state = driver.find_element_by_id('billing_state')
state.send_keys("Moscow")
zip = driver.find_element_by_id('billing_postcode')
zip.send_keys("123456")
driver.execute_script("window.scrollBy(0, 600);")
time.sleep(3)
pay = driver.find_element_by_id('payment_method_cod')
pay.click()
order = driver.find_element_by_id('place_order')
order.click()
message = WebDriverWait(driver, 10).until(
EC.text_to_be_present_in_element((By.CLASS_NAME, "woocommerce-thankyou-order-received"), "Thank you. Your order has been received."))
payment = WebDriverWait(driver, 10).until(
EC.text_to_be_present_in_element((By.CLASS_NAME, "method"), "Cash on Delivery"))
driver.quit()